### ISSUE TITLE
App manager don't block trackers in Lineage 21 (Android 14)

### ISSUE THREAD

**Issue by mauriicio3** [amcommunity/TipsAndTricks#19]
App manager don't block trackers in Lineage 21 (Android 14).
At least, that was my experience.
I searched for any solution, but no success.
I've had to return to Lineage 20, which App Manager works perfectly.
Sorry my english.

**Comment by MuntashirAkon** [comment]
This is not an issue-tracker, use https://github.com/MuntashirAkon/AppManager/issues. This issue shall be deleted as it's not relevant here.
